# Generated by Django 3.2.9 on 2021-11-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_alter_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameratings',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='raterapi.games'),
        ),
    ]
